### ISSUE TITLE
building modules fail

### ISSUE THREAD

**Issue by jrishel** [RedHatSatellite/pumsu#5]
running this command fails while trying to build modules:

```
./pumsu --modules /modules/modules.txt --source /modules/ --repoid 1459
[*] resetting permissions in source directory
[*] building module: puppet-module-1
Traceback (most recent call last):
  File "/downloads/pumsu/pumsu", line 201, in <module>
    rc = main()
  File "/downloads/pumsu/pumsu", line 171, in main
    copy(glob("pkg/*.tar.gz")[0], out_dir)
IndexError: list index out of range
```

appears that line 168 has changed to no longer run "puppet module build" because running that on the command line now gives me:

```
 puppet module build
Error: This action has been replaced by Puppet Development Kit. For more information visit https://puppet.com/docs/pdk/latest/pdk.html.
Error: Try 'puppet help module build' for usage
```

**Comment by jrishel** [comment]
taking a look at this similar issue: https://access.redhat.com/solutions/5619641
